apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-acr
  name: nginx-acr
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-acr
  ports:
    - port: 80
      targetPort: 80