apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx-app
  name: azurefile-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-sc
  resources:
    requests:
      storage: 5Gi