apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: azure-file-nginx
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80