apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nginx-app
  name: azurefile-sc
  namespace: default
provisioner: file.csi.azure.com
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS