apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-web-app
  name: todo-web-app
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: todo-web-app
  template:
    metadata:
      labels:
        app: todo-web-app
    spec:
      containers:
        - env:
            - name: RDS_DB_NAME
              value: todos
            - name: RDS_HOSTNAME
              value: mysql
            - name: RDS_PASSWORD
              value: dummytodos
            - name: RDS_PORT
              value: "3306"
            - name: RDS_USERNAME
              value: todos-user
          name: todo-web-app
          image: alexisgf/todo-web-application-mysql:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: todo-web-app
      restartPolicy: Always