apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app1
  name: nginx-app1
  namespace: dev2
spec:
  type: LoadBalancer
  selector:
    app: nginx-app1
  ports:
    - port: 80
      targetPort: 80