apiVersion: v1
kind: Secret
metadata:
  labels:
    app: mysql
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_PASSWORD: ZHVtbXl0b2Rvcw==
  MYSQL_ROOT_PASSWORD: ZHVtbXlwYXNzd29yZA==