apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app2
  name: nginx-app2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: nginx-app2
  ports:
    - port: 80
      targetPort: 80