apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: azure-managed-disk-pvc
  name: azure-managed-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium-retain-sc-mysql
  resources:
    requests:
      storage: 5Gi