apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: mysql
  name: managed-premium-retain-sc-mysql
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed