apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world-rest-api
  ports:
  - port: 8080
    targetPort: 8080