apiVersion: v1
kind: LimitRange
metadata:
  labels:
    app: dev3
  name: default-cpu-mem-limit-range
  namespace: dev3
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi